### ISSUE TITLE
HomePage Ui Fix.

### ISSUE THREAD

**Issue by Asharalikhan4** [Asharalikhan4/JavaScript#24]
Here we have some space which making the homepage scrollable, so what i want is that the text part on the Homepage/Landing page should be in center vertically and horizontally and there should be no place left for scrolling.

Added video of the issue for better understanding.

https://github.com/user-attachments/assets/5447789c-9c17-4fd6-bec8-ad5fc612c4da

**Comment by GeorgiosDrivas** [comment]
Hello @Asharalikhan4 ! I would like to work on this issue.

**Comment by Asharalikhan4** [comment]
Assigned it to you, @GeorgiosDrivas.

**Comment by Asharalikhan4** [comment]
Merged.
